services:
  auth-service:
    build: ./packages/auth
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - API_JWT_SECRET=${API_JWT_SECRET}
    ports:
      - ${AUTH_SERVICE_PORT}:80
    depends_on:
      - postgres-db

  shortener-service:
    build: ./packages/shortener
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - API_JWT_SECRET=${API_JWT_SECRET}
    volumes:
      - ./packages/shortener:/app
    ports:
      - ${SHORTENER_SERVICE_PORT}:80
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./packages/db/init.sql:/docker-entrypoint-initdb.d/init.sql
