version: '3'


services:
  auth-service:
    build: ./packages/auth
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${AUTH_SERVICE_PORT}:80
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
      - ./packages/db/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  my-network:  # Define a network for service discovery
    external: true  # Optional: Allow external connections to the network